# Generated by Django 4.0.4 on 2022-05-25 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inbox', '0004_alter_inbox_last_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='user',
            field=models.ManyToManyField(related_name='users', through='inbox.Inbox_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
