# Generated by Django 4.0.4 on 2022-05-28 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_alter_inbox_participants_inbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox_participants',
            name='inbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inbox.inbox'),
        ),
    ]
