# Generated by Django 4.0.4 on 2022-05-25 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
        ('inbox', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='last_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inboxes', to='message.message'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='user',
            field=models.ManyToManyField(through='inbox.Inbox_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
