# Generated by Django 4.0.4 on 2022-05-28 19:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inbox', '0008_alter_inbox_participants_inbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='user',
        ),
        migrations.AddField(
            model_name='inbox',
            name='users',
            field=models.ManyToManyField(related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Inbox_participants',
        ),
    ]
