# Generated by Django 4.0.4 on 2022-05-28 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0009_remove_inbox_user_inbox_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='users',
            new_name='user',
        ),
    ]
