# Generated by Django 4.0.4 on 2022-05-28 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inbox', '0010_rename_users_inbox_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='user',
        ),
        migrations.AddField(
            model_name='inbox',
            name='users',
            field=models.ManyToManyField(related_name='inboxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
