# Generated by Django 4.0.4 on 2022-05-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_user'),
        ('inbox', '0011_remove_inbox_user_inbox_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='users',
        ),
        migrations.AddField(
            model_name='inbox',
            name='profiles',
            field=models.ManyToManyField(related_name='inboxes', to='profiles.profile'),
        ),
    ]
